<a href="https://colab.research.google.com/github/sak1b0/Thesis/blob/master/LabelEncoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

url='https://raw.githubusercontent.com/sak1b0/Thesis/master/allCSV/abalone.csv'

#dataframe hisebe read hocche
df=pd.read_csv(url,header=None,nrows=10)

#clm,row order
print(df.values)


#testing block start

df=df.values
print('\n============ after encoding =============\n')

#hot=OneHotEncoder(column_transformer=[0])
#df=hot.fit_transform(df).toarray()
lbl=LabelEncoder()
df[:,0] = lbl.fit_transform(df[:,0])
print(df)


#testing block end


[['M' 0.455 0.365 0.095 0.514 0.2245 0.10099999999999999 0.15 15]
 ['M' 0.35 0.265 0.09 0.2255 0.0995 0.0485 0.07 7]
 ['F' 0.53 0.42 0.135 0.677 0.2565 0.1415 0.21 9]
 ['M' 0.44 0.365 0.125 0.516 0.2155 0.114 0.155 10]
 ['I' 0.33 0.255 0.08 0.205 0.0895 0.0395 0.055 7]
 ['I' 0.425 0.3 0.095 0.3515 0.141 0.0775 0.12 8]
 ['F' 0.53 0.415 0.15 0.7775 0.237 0.1415 0.33 20]
 ['F' 0.545 0.425 0.125 0.768 0.294 0.1495 0.26 16]
 ['M' 0.475 0.37 0.125 0.5095 0.2165 0.1125 0.165 9]
 ['F' 0.525 0.38 0.14 0.6065 0.19399999999999998 0.1475 0.21 14]]

============ after encoding =============

[[2 0.455 0.365 0.095 0.514 0.2245 0.10099999999999999 0.15 15]
 [2 0.35 0.265 0.09 0.2255 0.0995 0.0485 0.07 7]
 [0 0.53 0.42 0.135 0.677 0.2565 0.1415 0.21 9]
 [2 0.44 0.365 0.125 0.516 0.2155 0.114 0.155 10]
 [1 0.33 0.255 0.08 0.205 0.0895 0.0395 0.055 7]
 [1 0.425 0.3 0.095 0.3515 0.141 0.0775 0.12 8]
 [0 0.53 0.415 0.15 0.7775 0.237 0.1415 0.33 20]
 [0 0.545 0.425 0.125 0.768 0.294 0.1495 0.26 16]
 [2 0.4