<a href="https://colab.research.google.com/github/sak1b0/Thesis/blob/master/step1_beta1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

url='https://raw.githubusercontent.com/sak1b0/Thesis/master/allCSV/abalone.csv'

df=pd.read_csv(url,header=None)


#----------to handle nominal values---------

my_arr=[]

#track of column indices 
index=0
for item in df.dtypes:
  if(item=='object'):
    #if data type is nominal adding to the array
    my_arr.append(index)
  index=index+1
  
print('object data types: ',len(my_arr))

df=df.values

if(len(my_arr)>0):
  lbl=LabelEncoder()
  for item in my_arr:
    df[:,item] = lbl.fit_transform(df[:,item])
    
  print(df)    
#--------------------------------------------


df=np.asarray(df)

X, y = np.split(df,[-1],axis=1)
#issue here !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
y=y.astype('float64')

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

#to check additional info set the value of debug to 1
debug=0

if(debug==1):
  print('----------debug start----------')
  print('main data: ',data.shape)
  print('x: ',X.shape)
  print('y: ',y.shape)
  print('x_train: ',x_train.shape)
  print('x_test: ',x_test.shape)
  print('y_train: ',y_train.shape)
  print('y_test: ',y_test.shape)
  print('----------debug end----------')




# X=np.asarray(X)
# y=np.asarray(y)
# y=y.ravel() #vector to array

x_train=np.asarray(x_train)
x_test=np.asarray(x_test)
y_train=np.asarray(y_train)
y_test=np.asarray(y_test)
y_train=y_train.ravel()
y_test=y_test.ravel()


#model = MultinomialNB()
model = GaussianNB()
model.fit(x_train,y_train)
expected = y_test
predicted = model.predict(x_test)
print(metrics.classification_report(expected, predicted))
#print(metrics.confusion_matrix(expected, predicted))

object data types:  1
[[2 0.455 0.365 ... 0.10099999999999999 0.15 15]
 [2 0.35 0.265 ... 0.0485 0.07 7]
 [0 0.53 0.42 ... 0.1415 0.21 9]
 ...
 [1 0.39 0.31 ... 0.0695 0.079 7]
 [1 0.475 0.365 ... 0.0885 0.156 10]
 [2 0.56 0.43 ... 0.172 0.22899999999999998 8]]
              precision    recall  f1-score   support

         3.0       0.33      0.67      0.44         3
         4.0       0.06      0.33      0.11         3
         5.0       0.24      0.53      0.33        19
         6.0       0.28      0.30      0.29        63
         7.0       0.29      0.37      0.33        78
         8.0       0.25      0.32      0.28       125
         9.0       0.27      0.29      0.28       132
        10.0       0.22      0.22      0.22       116
        11.0       0.27      0.46      0.34       103
        12.0       0.00      0.00      0.00        59
        13.0       0.00      0.00      0.00        43
        14.0       0.00      0.00      0.00        22
        15.0       0.00      0.00  

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
