<a href="https://colab.research.google.com/github/sak1b0/Thesis/blob/master/step1_beta1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

url='https://raw.githubusercontent.com/sak1b0/Thesis/master/allCSV/adult.csv'

df=pd.read_csv(url,header=None)


#----------to handle nominal values---------

my_arr=[]

#track of column indices 
index=0
for item in df.dtypes:
  if(item=='object'):
    #if data type is nominal adding to the array
    my_arr.append(index)
  index=index+1
  
print('object data types: ',len(my_arr))

df=df.values

if(len(my_arr)>0):
  lbl=LabelEncoder()
  for item in my_arr:
    df[:,item] = lbl.fit_transform(df[:,item])
    
  print(df)    
#--------------------------------------------


df=np.asarray(df)

X, y = np.split(df,[-1],axis=1)
#issue here !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
y=y.astype('float64')

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

#to check additional info set the value of debug to 1
debug=0

if(debug==1):
  print('----------debug start----------')
  print('main data: ',data.shape)
  print('x: ',X.shape)
  print('y: ',y.shape)
  print('x_train: ',x_train.shape)
  print('x_test: ',x_test.shape)
  print('y_train: ',y_train.shape)
  print('y_test: ',y_test.shape)
  print('----------debug end----------')




# X=np.asarray(X)
# y=np.asarray(y)
# y=y.ravel() #vector to array

x_train=np.asarray(x_train)
x_test=np.asarray(x_test)
y_train=np.asarray(y_train)
y_test=np.asarray(y_test)
y_train=y_train.ravel()
y_test=y_test.ravel()


#model = MultinomialNB()
model = GaussianNB()
model.fit(x_train,y_train)
expected = y_test
predicted = model.predict(x_test)
print(metrics.classification_report(expected, predicted))
#print(metrics.confusion_matrix(expected, predicted))

object data types:  9
[[25.0 2 226802.0 ... 40.0 38 0]
 [38.0 2 89814.0 ... 50.0 38 0]
 [28.0 1 336951.0 ... 40.0 38 1]
 ...
 [58.0 2 151910.0 ... 40.0 38 0]
 [22.0 2 201490.0 ... 20.0 38 0]
 [52.0 3 287927.0 ... 40.0 38 1]]
              precision    recall  f1-score   support

         0.0       0.81      0.95      0.87      6772
         1.0       0.68      0.32      0.44      2273

   micro avg       0.79      0.79      0.79      9045
   macro avg       0.74      0.64      0.65      9045
weighted avg       0.77      0.79      0.76      9045

